### PR TITLE
Allow setting GPU layers through the API

### PR DESCRIPTION
**Pull request by Pyroglyph**
This PR enables setting GPU layers through the API by passing a breakmodel layer string alongside the model name.

I'm not a Python developer so if something looks odd that's why. However, I've done some testing locally and it seems to work fine without any errors.

### CODE REVIEW

**Comment by henk717** [comment]
When testing this I get the following error:
```
[2023-05-15 22:52:39,678] ERROR in app: Exception on /api/v1/model [PUT]
Traceback (most recent call last):
  File "B:\python\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "B:\python\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "B:\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "B:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "aiserver.py", line 774, in g
    return f(*args, **kwargs)
  File "aiserver.py", line 696, in decorated
    response = f(schema, *args, **kwargs)
  File "aiserver.py", line 679, in decorated
    raise e
  File "aiserver.py", line 670, in decorated
    return f(*args, **kwargs)
  File "aiserver.py", line 8674, in put_model
    raise e
  File "aiserver.py", line 8670, in put_model
    use_gpu = len(body.gpu_layers) > 0 and sum(map(int, body.gpu_layers.split(","))) > 0
AttributeError: type object 'GeneratedSchema' has no attribute 'gpu_layers'
```

**Comment by Pyroglyph** [comment]
My bad, I did the testing on the main branch instead of united. This should work now.

**Comment by ebolam** [comment]
Note this will need to be reworked with the model backends change. (PR #362)

**Comment by henk717** [comment]
Closed for now since its not compatible with the newer backend, feel free to resubmit once updated

**Pull request closed without merging**
