### PR TITLE
Add AdventureMode stopper

### PR DESCRIPTION
**Pull request by YellowRoseCx**
Stops at "> You " and "You:" when adventure mode is enabled
        
Was useful for me

### CODE REVIEW

**Comment by henk717** [comment]
I think this will be useful but since it touches the backend I am going to put this on hold until the backend changes are in.

**Comment by YellowRoseCx** [comment]
modified for new backend

**Comment by henk717** [comment]
Adventure mode responses can be more dynamic, we don't want to block You on a new line because thats what Skein often does.
Simply stopping at > is enough since thats what the UI cleanup code does.

**Comment by YellowRoseCx** [comment]
> Adventure mode responses can be more dynamic, we don't want to block You on a new line because thats what Skein often does. Simply stopping at > is enough since thats what the UI cleanup code does.

The reason I added You is because I was having several models continue on with choices , generating output as me, because it didn't have > in front of it. When I was testing it, I couldn't think of a scenario where this would break normal play

**Comment by henk717** [comment]
Traditional adventure models like AI Dungeon's model have an extreme You bias.
```
> You kill the dragon
You step towards the dragon with your sword and cut off its head.
```
A proper adventure mode basically interperates your instruction and does a varient off it.

**Comment by YellowRoseCx** [comment]
> Traditional adventure models like AI Dungeon's model have an extreme You bias.
> 
> ```
> > You kill the dragon
> You step towards the dragon with your sword and cut off its head.
> ```

Yeah that would still work, before it would be like:

```
> You kill the dragon
You step towards the dragon with your sword and cut off its head. 

You cut off its skin and pack it away in its bag before leaving the cave. Outside the cave you see a man in the distance who saw you kill the dragon.

You shout towards the man and he starts running away
```
Etc

It's been a while since I last tested this but I believe I tuned it so it will not stop at the first sentence that starts with You because of the stopper having 2 newlines in it

**Pull request merged**
