### PR TITLE
Actually create a new blank story

### PR DESCRIPTION
**Pull request by jojorne**
This fixes WI leaking when creating a new story and resets all story variables.

Known issues:
- [x] The UI is not updating correctly

### CODE REVIEW

**Comment by jojorne** [comment]
I'm resetting save overwrite here for https://github.com/henk717/KoboldAI/pull/308 (forgot to put it there >.<')

**Comment by henk717** [comment]
I don't see what this fixes, but it definately causes more leaks with for example the memory not clearing.

**Comment by jojorne** [comment]
Creating a new story resets everything about the story.  See, I've had cases where it overwrites my last saved story file thinking it was the same story and also the AI ​​using the last story's WI entries with no way to remove those entries.

For the memory leak, if using `gc.collect()` inside create_story doesn't help then there's something else using the reference. There is another place using create_story that could be suffering the same memory leak.

**Comment by henk717** [comment]
Not that kind of memory leak, when the variables are cleared this is sent to the browser. On your commit it is not cleared from the browser interface correctly, so if you look at the memory tab it is still visible while on current United it does get cleared properly.

I assume its caused by the lines that got incorrectly removed in this commit.

**Comment by jojorne** [comment]
Oooh, I see! The variables removed are all resting inside create_story. I thought create_story was sending the info to the clients. Thanks!

**Comment by jojorne** [comment]
Loading the "sample_story" sets some memory, then clicking create a new blank story resets it. So I couldn't reproduce it in my local build.

**Pull request closed without merging**
