### PR TITLE
Adding CORS support to allow cross origin requests.

### PR DESCRIPTION
**Pull request by LostRuins**
Adding CORS support to allow cross origin requests. 
This will allow browser based clients to interface with local installations of kobold. Python scripts (e.g. the existing horde bridge) are not affected by CORS and are already able to do so.

Also added new dependency for the required `flask-cors` package

### CODE REVIEW

**Comment by ebolam** [comment]
What's the purpose of this (other than extending features). Is there a specific use case in mind? Also, what security implications would this bring?

**Comment by LostRuins** [comment]
Hi @ebolam , the main purpose is to allow browser based clients (such as KoboldAI Lite https://lite.koboldai.net) to optionally connect to the user's own local Kobold instances without having to go through the Horde.

Secondary uses are also introducing the possibility of running custom web-based horde bridges, a capability currently only exclusive to db0's python bridge.

Security implications would allow Javascript running on webpages in a browser to connect to the local kobold instance. As there is currently no authentication required, a normal desktop application and python scripts are already permitted to do so, however currently web browsers are not. 

I believe the risk is low as it is unlikely there is any privacy sensitive information accessible through the kobold api.

Have [previously suggested](https://discord.com/channels/849937185893384223/849938567349796874/1069292951555027004) this to @henk717 , thought i'd go ahead and create a PR for this first since it's relatively straightforward. My discord username is Concedo.

**Comment by ebolam** [comment]
We would need to add some security to this as the API can be used to get the current story as well as load stories, so if this was in and the server was accessible from the internet then anyone could gain access to the story and potentially drop files on the server.

**Comment by LostRuins** [comment]
Yep that is a valid concern especially if running on a known localhost port. 

Alright then, I think no code changes needed for now then, we can revisit this in future if necessary. Thanks.

You may close this pull request, or leave it open to discuss again in future.

**Pull request merged**
